name             "chruby"
maintainer       "Atalanta Systems Ltd"
maintainer_email "support@atalanta-systems.com"
license          "Apache 2.0"
description      "Installs and configures the chruby tool for managing Ruby versions"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.2.1"
depends          "ark"
depends          "ruby_build"
supports         "centos",          "= 6.3"
supports         "centos",          "= 5.8"
supports         "ubuntu",          "= 10.04"
supports         "ubuntu",          "= 12.04"
provides         "chruby_execute"
provides         "chruby_gem_package"
recipe           "chruby::default", "Install chruby"
recipe           "chruby::system",  "Install chruby and configured Ruby versions"
